apiVersion: v1
kind: Service
metadata:
  name: microservices-okteto-backend-login
spec:  
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      name: http
  selector:
    app: microservices-okteto-backend-login